#ifndef SQLCOMMANDS_H_INCLUDED
#define SQLCOMMANDS_H_INCLUDED



#define CREATE_TABLE_COMMAND "CREATE TABLE IF NOT EXISTS"
#define INSERT_IN_TABLE_COMMAND "INSERT INTO"
#define SELECT_FROM_TABLE_COMMAND "SELECT * FROM"
#define DELETE_FROM_TABLE_COMMAND "DELETE FROM"



#define WHERE_EXPRESSION_COMMAND "WHERE"

#endif // SQLCOMMANDS_H_INCLUDED
